image_width: 1920
image_height: 1200
camera_name: Camera_1
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1186.41663,     0.     ,   956.37139,
             0.     ,  1189.63895,   579.23666,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.223013, 0.070276, -0.000136, 0.000023, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1016.80371,     0.     ,   955.53749,     0.     ,
             0.     ,  1120.13342,   576.4846 ,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]


# image_width: 1920
# image_height: 1200
# camera_name: Camera_1
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [ 1186.88624,     0.     ,   939.34595,
#              0.     ,  1189.50325,   576.59108,
#              0.     ,     0.     ,     1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.222406, 0.069061, 0.000457, 0.000153, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [ 1.,  0.,  0.,
#           0.,  1.,  0.,
#           0.,  0.,  1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [ 1016.69159,     0.     ,   934.59218,     0.     ,
#              0.     ,  1120.06555,   574.19007,     0.     ,
#              0.     ,     0.     ,     1.     ,     0.     ]



# image_width: 1920
# image_height: 1200
# camera_name: Camera_1
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1.,     0.,   0.,
#          0.,     1.,   0.,
#          0.,     0.,   1. ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [0., 0., 0., 0., 0.]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1.,     0.,   0.,
#          0.,     1.,   0.,
#          0.,     0.,   1. ]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1.,     0.,   0.,  0.,
#          0.,     1.,   0.,  0.,
#          0.,     0.,   1.,  0. ]


